// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Note: Currently only web platform is configured.
    // To add iOS/Android support, run: flutterfire configure
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android platform not configured. Run `flutterfire configure` to add support.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS platform not configured. Run `flutterfire configure` to add support.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS platform not configured. Run `flutterfire configure` to add support.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows platform not configured. Run `flutterfire configure` to add support.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux platform not configured. Run `flutterfire configure` to add support.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqprST_hEViAMJEcgcaN8d1FkLeT0IdI',
    appId: '1:572391915409:web:5399654904b6baefd16430',
    messagingSenderId: '572391915409',
    projectId: 'sweets-c4f6b',
    authDomain: 'sweets-c4f6b.firebaseapp.com',
    storageBucket: 'sweets-c4f6b.firebasestorage.app',
    measurementId: 'G-1RW2CLLKT7',
  );
}
